apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-request
  labels:
    app.kubernetes.io/name: fake-request
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fake-request
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fake-request
    spec:
      containers:
        - name: fake-request
          image: fake-request-example-demo:v1
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: demo-fb-config
          configMap:
            name: demo-fb-config
