apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: opensearch-system

resources:
  - ../../base

patchesStrategicMerge:
  - limits.yaml
  - replicas.yaml
  - volumes.yaml

secretGenerator:
  - name: internal-users-secret
    files:
      - internal_users.yaml

generatorOptions:
  disableNameSuffixHash: true
