apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-cluster-master
spec:
  template:
    spec:
      containers:
        - name: opensearch
          resources:
            requests:
              cpu: 1000m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
