apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-cluster-master
spec:
  template:
    spec:
      containers:
        - name: opensearch
          volumeMounts:
            - mountPath: /usr/share/opensearch/config/opensearch-security/internal_users.yml
              name: internal-users-secret
              subPath: internal_users.yml
      volumes:
        - name: internal-users-secret
          secret:
            secretName: internal-users-secret
        - emptyDir: {}
          name: ca-cert
