apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opensearch
    namespace: opensearch-system
    includeCRDs: true
    releaseName: opensearch
    version: 2.6.2
    valuesFile: values.yaml
    repo: https://opensearch-project.github.io/helm-charts/
