---
# Source: opensearch/charts/opensearch/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "opensearch-cluster-master"
subjects:
  - kind: ServiceAccount
    name: "opensearch-sa"
    namespace: "default"
roleRef:
  kind: Role
  name: "opensearch-cluster-master"
  apiGroup: rbac.authorization.k8s.io
