apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opensearch-system

resources:
  - ./namespace.yaml

bases:
  - ./opensearch
  - ./opensearch-dashboards
  - ./kustomize-certs
  - ./kustomize-rbac

patches:
  - target:
      name: opensearch.*
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "90"
