apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opensearch-system
namePrefix: opensearch-
resources:
  - sa.yaml
  # Generally we do not need psp so here is optional to create RBAC
  # - role.yaml
  # - rolebinding.yaml
