apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: opensearch-system
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    countries:
      - CN
    organizations:
      - Personal Demo
  commonName: your-domain-here.com
  dnsNames: []
  secretName: opensearch-tls-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
