apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: not-important.io
  secretName: opensearch-ca-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2948
  issuerRef:
    name: opensearch-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-from-ca
spec:
  ca:
    secretName: opensearch-ca-key-pair
