apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: opensearch-system
namePrefix: opensearch-
resources:
  - self-signed-cert.yaml
  - opensearch-cert.yaml
  - opensearch-dashboard.yaml
patches:
  - path: dns-patch.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
