apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/name: demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: demo
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo
    spec:
      initContainers:
        - name: loginit
          image: busybox:1.34
          command:
            - touch
            - /mnt/log/app_log.log
          volumeMounts:
            - name: varlog
              mountPath: /mnt/log
      containers:
        - name: demo
          image: demo
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://opentelemetry-collector-demo-collector.opentelemetry-collector-demo.svc.cluster.local:4317"
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: varlog
              mountPath: /python-docker/log
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
        - name: fluent-bit
          image: fluent/fluent-bit:1.9.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
          env:
            - name: FLUENT_OPENSEARCH_HOST
              # value: "data-prepper.opensearch-system.svc.cluster.local"
              value: "opensearch-cluster-master.opensearch-system.svc.cluster.local"
            - name: FLUENT_OPENSEARCH_PORT
              value: "9200"
            - name: FLUENT_OPENSEARCH_USER
              value: "admin"
            - name: FLUENT_OPENSEARCH_PASSWORD
              value: "admin"
            - name: FLUENT_OPENSEARCH_PREFIX
              value: "log-demo"
            - name: FLUENT_BIT_FORWARD
              value: "fluentbit-fluent-bit.fluent-system.svc.cluster.local"
            - name: FLUENT_TAG
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: demo-fb-config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /mnt/log
              readOnly: true
      volumes:
        - name: demo-fb-config
          configMap:
            name: demo-fb-config
        - name: varlog
          emptyDir: {}
