apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo2

resources:
- python-sidecar-fb-forward-config.yaml
- deployment.yaml
  # - prom-servicemonitor.yaml
images:
- name: demo
  newName: flask-example-demo
  newTag: otlp-agent-v2
