apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-fb-config
  labels:
    app.kubernetes.io/name: demo-fb-config
    app.kubernetes.io/managed-by: kustomize
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush         5
      Log_Level     debug
      Daemon        off
      Parsers_File  parsers.conf

    @INCLUDE input.conf
    @INCLUDE filter.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
      Name              tail
      Tag               ${FLUENT_TAG}
      Path              /mnt/log/app_log.log
      Parser            wsgi
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Refresh_Interval  10

  output.conf: |
    [OUTPUT]
      Name          forward
      Match         *
      Host          ${FLUENT_BIT_FORWARD}
      Port          24224
      Self_Hostname flb.local

  parsers.conf: |
    [PARSER]
      Name wsgi
      Format regex
      Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)$
      Time_Key time
      Time_Format %d/%b/%Y %H:%M:%S
      Types code:integer

  filter.conf: |
    [FILTER]
      Name    grep
      Match   *
      Regex   path .*
