apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-data-prepper-http
  labels: 
    {{- include "data-prepper.labels" . | nindent 4 }}
stringData:
  pipelines.yaml: |-
    log-pipeline:
      workers: 1
      delay: 1000
      source:
        http:
          ssl: false
      prepper:
        - grok:
            match:
              log: [ "%{COMMONAPACHELOG}" ]
      sink:
        - opensearch:
            hosts: [ {{ .Values.opensearch.host }} ]
            username: {{ .Values.opensearch.user }}
            password: {{ .Values.opensearch.password }}
            insecure: true
            index: log-demo
