apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-data-prepper-oltp
  labels: 
    {{- include "data-prepper.labels" . | nindent 4 }}
stringData:
  pipelines.yaml: |-
    entry-pipeline:
      workers: 2
      delay: 1000
      source:
        otel_trace_source:
          ssl: true
          sslKeyCertChainFile: "/usr/share/data-prepper/certs/server.crt"
          sslKeyFile: "/usr/share/data-prepper/certs/server.key"
          port: 21890
      buffer:
        bounded_blocking:
          buffer_size: 1024 # max number of records the buffer accepts
          batch_size: 256 # max number of records the buffer drains after each read
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - otel_trace_raw_prepper:
      sink:
        - opensearch:
            hosts: [ {{ .Values.opensearch.host }} ]
            cert: "/usr/share/data-prepper/certs/root-ca.pem"
            username: {{ .Values.opensearch.user }}
            password: {{ .Values.opensearch.password }}
            trace_analytics_raw: true
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: [ {{ .Values.opensearch.host }} ]
            cert: "/usr/share/data-prepper/certs/root-ca.pem"
            username: {{ .Values.opensearch.user }}
            password: {{ .Values.opensearch.password }}
            trace_analytics_service_map: true