apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-prepper.fullname" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: otlp
  selector:
    {{- include "data-prepper.selectorLabels" . | nindent 4 }}
